packages:
  - 'packages/*'

allowBuilds:
  '@apollo/protobufjs': false
  '@firebase/util': false
  '@nestjs/core': false
  '@scarf/scarf': false
  bcrypt: false
  protobufjs: false
  unrs-resolver: false
