apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # Communicates over the internal Docker network using the service name
    url: http://prometheus:9090
    isDefault: true
    editable: true
